/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/pages/Home.vue')['default']
    Login: typeof import('./src/pages/Login.vue')['default']
    ModalTemplate: typeof import('./src/components/modal/ModalTemplate.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NoteCard: typeof import('./src/components/note/NoteCard.vue')['default']
    NoteDropdown: typeof import('./src/components/dropdown/NoteDropdown.vue')['default']
    NoteFilterDropdown: typeof import('./src/components/dropdown/NoteFilterDropdown.vue')['default']
    NoteModal: typeof import('./src/components/modal/NoteModal.vue')['default']
    NotFound: typeof import('./src/pages/fallback/not-found.vue')['default']
    NSpin: typeof import('naive-ui')['NSpin']
    ProfileDropdown: typeof import('./src/components/dropdown/ProfileDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signup: typeof import('./src/pages/Signup.vue')['default']
  }
}
